name: Helm Deployment
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

env:
  AZURE_CONTAINER_REGISTRY: "akstest03" # set this to the name of your container registry
  PROJECT_NAME: "aks-test-rg"              # set this to your project's name
  AKS_RESOURCE_GROUP: "aks-test-rg"       # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: "aks-cibg-dev-uan-1"             # set this to the name of your AKS cluster
  REGISTRY_URL: "akstest03.azurecr.io"            # set this to the URL of your registry

  # If you bake using helm:
  CHART_PATH: "flask-helm"                   # set this to the path to your helm file
  CHART_OVERRIDE_PATH: "flask-helm/values.yaml"     # set this to an array of override file paths

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'

      - name: Gets K8s context
        uses: Azure/aks-set-context@v4.0.0
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
        id: login

      - name: Configure deployment
        id: bake
        uses: Azure/k8s-bake@v3.0.0
        with:
          renderEngine: 'helm'
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            replicas: 2
            image: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PROJECT_NAME }}
            imageTag: latest
          helm-version: 'latest'

      - name: Deploys application
        uses: Azure/k8s-deploy@v5.0.0
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
#          imagepullsecrets: |
#            ${{ env.PROJECT_NAME }}
