name: Helm Deployment
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

env:
  AZURE_CONTAINER_REGISTRY: "helmregistryaks" # set this to the name of your container registry
  PROJECT_NAME: "AKS-Deploy"              # set this to your project's name
  AKS_RESOURCE_GROUP: "aks-helm-test-rg"       # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: "helm-test-aks"             # set this to the name of your AKS cluster
  REGISTRY_URL: "helmregistryaks.azurecr.io"            # set this to the URL of your registry

  # If you bake using helm:
  CHART_PATH: "flask-helm"                   # set this to the path to your helm file
  CHART_OVERRIDE_PATH: "flask-helm/values.yaml"     # set this to an array of override file paths

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Build image on ACR
        uses: azure/CLI@61bb69d64d613b52663984bf12d6bac8fd7b3cc8
        with:
          azcliversion: 2.29.1
          inlineScript: |
            az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
            az acr build -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:latest --file aks-test-app/Dockerfile

      - name: Gets K8s context
        uses: Azure/aks-set-context@v4.0.0
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
        id: login

      - name: Configure deployment
        id: bake
        uses: Azure/k8s-bake@v3.0.0
        with:
          renderEngine: 'helm'
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            replicas:2
          helm-version: 'latest'

      - name: Deploys application
        uses: Azure/k8s-deploy@v5.0.0
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PROJECT_NAME }}:latest
#          imagepullsecrets: |
#            ${{ env.PROJECT_NAME }}