name: Helm Deployment
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

env:
  PROJECT_NAME: "flask-app"
  CHART_PATH: "flask-helm"
  CHART_OVERRIDE_PATH: "flask-helm/values.yaml"

jobs:
  Helm-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Set k8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Configure deployment
        id: bake
        uses: Azure/k8s-bake@v3.0.0
        with:
          renderEngine: 'helm'
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            replicas: 3
            image: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PROJECT_NAME }}
            imageTag: latest
          helm-version: 'latest'

      - name: Deploy application
        uses: Azure/k8s-deploy@v5.0.0
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
#          imagepullsecrets: |
#            ${{ env.PROJECT_NAME }}
